services:
    mongo:
      image: mongo
      restart: always
      volumes:
        - mongo-data:/data/db
      ports:
        - 27017:27017
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: abc123

volumes:
    mongo-data: