services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "DB"
      POSTGRES_USER: "shreyash"
      POSTGRES_PASSWORD: "abc123"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local